[package]
name = "vire"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
fjall = { version = "3.0.1", features = ["lz4"] }
libp2p = { version = "0.56.0", features = ["gossipsub", "noise", "tcp", "yamux", "macros", "tokio"] }
rand = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
ucan = "0.4.0"

[dev-dependencies]
tempfile = "3.24.0"
turmoil = "0.7.0"
