[package]
name = "vire"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = "0.56.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[dev-dependencies]
turmoil = "0.7.0"
